[mainConfig]
appName = "GopherAI"
host = "0.0.0.0"
port = 9090

[emailConfig]
authcode = "kjxmdpqumwsngocx"
email = "danae0730@gmail.com"
smtpHost = "smtp.gmail.com"
smtpPort = 587

[redisConfig]
host = "127.0.0.1"
port = 6379
password = ""
db = 0

[mongoConfig]
host = "127.0.0.1"
port = 27017
user = ""
password = ""
databaseName = "GopherAI"

[jwtConfig]
 expire_duration= 8760
 issuer= "huanheart"
 subject= "GopherAI"
 key= "GopherAI-v1"

 [rabbitmqConfig]
  host= "127.0.0.1"
  port= 5672
  username= "root"
  password= "123456"
  vhost= "/"
